# Generated by Django 6.0.5 on 2026-05-11 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_materia_created_at_materia_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.PositiveIntegerField(verbose_name='duração')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('data_estudo', models.DateField(auto_now_add=True, verbose_name='data do estudo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='studies.materia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_estudo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Estudo',
                'verbose_name_plural': 'Sessões de Estudo',
                'ordering': ['-created_at'],
            },
        ),
    ]
