# Generated by Django 6.0.5 on 2026-05-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_sessaoestudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoestudo',
            name='duracao',
            field=models.TimeField(verbose_name='duração'),
        ),
    ]
