# Generated by Django 6.0.5 on 2026-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_alter_sessaoestudo_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoestudo',
            name='duracao',
            field=models.DurationField(verbose_name='duração'),
        ),
    ]
